version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      development:
        patterns:
          - "pytest*"
          - "mypy*"
          - "ruff*"
          - "pre-commit*"
        update-types:
          - "minor"
          - "patch"
      production:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "mypy*"
          - "ruff*"
          - "pre-commit*"
        update-types:
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
