"""Hypothesis strategies for data model testing.

This module provides a modular, model-aware strategy system that closely aligns
with the Pydantic data models. Strategies are organized by model type for
better maintainability and reusability.
"""

# Import all strategies for convenient access
from .actors import (
    corporate_actor_patterns,
    invalid_actor_data,
    realistic_git_actors,
    valid_git_actor,
    valid_git_actor_email,
    valid_git_actor_name,
    valid_git_timestamp,
)
from .base import (
    non_empty_text,
    text_with_length,
    trimmed_text,
    valid_length_filter,
)
from .commits import (
    commit_with_ai_summary,
    conventional_commit_message,
    merge_commit,
    root_commit,
    valid_branch_names,
    valid_commit,
    valid_commit_message,
    valid_commit_summary,
    valid_tag_names,
)
from .files import (
    added_file,
    copied_file,
    deleted_file,
    empty_diff,
    invalid_file_modification_data,
    large_diff,
    modified_file,
    multi_file_diff,
    renamed_file,
    single_file_diff,
    unicode_file_path,
    valid_diff,
    valid_file_modification,
    valid_file_path,
    valid_line_counts,
    valid_patch_content,
)
from .metadata import (
    amend_change,
    cherry_pick_change,
    direct_change,
    initial_change,
    invalid_change_metadata,
    merge_change,
    merge_commit_metadata,
    octopus_change,
    rebase_change,
    revert_change,
    root_commit_metadata,
    signed_commit_metadata,
    squash_change,
    valid_branch_name,
    valid_change_metadata,
    valid_git_metadata,
    valid_pr_id,
)
from .utils import (
    extended_git_sha,
    full_git_sha,
    invalid_git_sha,
    invalid_gpg_signature,
    short_git_sha,
    valid_git_sha,
    valid_gpg_signature,
)

__all__ = [
    # File strategies
    "added_file",
    "amend_change",
    "cherry_pick_change",
    "commit_with_ai_summary",
    "conventional_commit_message",
    "copied_file",
    "corporate_actor_patterns",
    "deleted_file",
    "direct_change",
    "empty_diff",
    "extended_git_sha",
    "full_git_sha",
    "initial_change",
    "invalid_actor_data",
    "invalid_change_metadata",
    "invalid_file_modification_data",
    "invalid_git_sha",
    "invalid_gpg_signature",
    "large_diff",
    "merge_change",
    "merge_commit",
    "merge_commit_metadata",
    "modified_file",
    "multi_file_diff",
    "non_empty_text",
    "octopus_change",
    "realistic_git_actors",
    "rebase_change",
    "renamed_file",
    "revert_change",
    "root_commit",
    "root_commit_metadata",
    "short_git_sha",
    "signed_commit_metadata",
    "single_file_diff",
    "squash_change",
    "text_with_length",
    "trimmed_text",
    "unicode_file_path",
    "valid_branch_name",
    "valid_branch_names",
    "valid_change_metadata",
    "valid_commit",
    "valid_commit_message",
    "valid_commit_summary",
    "valid_diff",
    "valid_file_modification",
    "valid_file_path",
    "valid_git_actor",
    "valid_git_actor_email",
    "valid_git_actor_name",
    "valid_git_metadata",
    "valid_git_sha",
    "valid_git_timestamp",
    "valid_gpg_signature",
    "valid_length_filter",
    "valid_line_counts",
    "valid_patch_content",
    "valid_pr_id",
    "valid_tag_names",
]
